Added 'design_name' and 'adk' parameters to the ORFS steps and added 'ibex' to the example designs
mflowgen/mflowgen pull request #163
Opened 2024-07-03 01:55 UTC by dolendravikas08

- Added following items to the parameters section in .yml files of the ORFS steps
  - design_name: undefined
  - clock_period: 1.0
  - adk: undefined

- Appended make command with `DESIGN_CONFIG=./designs/$adk/$design_name/config.mk`

- Modified the `construct-open.py` with the appropriate 'adk' and 'design_names' 

- Added 'ibex' (a small 32 bit RISC-V CPU core with a two stage pipeline) to the example designs

2024-07-05 23:04 UTC, ctorng requested changes

2024-07-05 23:04 UTC, ctorng commented on designs/GcdUnit/construct-open.py
>      'adk'            : adk_name,
Add `orfs_platform` here

2024-07-05 23:04 UTC, ctorng commented on designs/GcdUnit/construct-open.py
> +  adk_name = 'nangate45'
Revert this

2024-07-05 23:04 UTC, ctorng commented on steps/orfs-docker-setup/configure.yml
> +  adk: undefined
orfs-docker-setup does not use these, so remove these...

2024-07-05 23:04 UTC, ctorng commented on steps/orfs-yosys-synthesis/configure.yml
> +  - docker exec $CONTAINER bash -c "cd flow && make synth DESIGN_CONFIG=./designs/$adk/$design_name/config.mk"
Change to $orfs_platform

2024-07-07 00:48 UTC, dolendravikas08 commented
Added "orfs_platform" as a parameter instead of using "adk".

2024-07-08 17:57 UTC, ctorng commented
Looks great! Go ahead and click rebase and merge!

2024-07-09 19:48 UTC, merged